apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pypi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypi
  template:
    metadata:
      labels:
        app: pypi
    spec:
      containers:
      - name: pypi-container
        image: pypiserver/pypiserver:v1.3.2
        args: ["-P", ".", "-a", ".", "-vv", "packages"]
        ports:
        - containerPort: 8080
          name: http
